
services:
  agent:
    build: .
    container_name: jarvis
    volumes:
      - ./app:/app/app
      - ./lib:/app/lib
    ports:
      - "8002:8002"
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
